# -*- coding: utf-8 -*-

# PROEJCT

DEBUG = True


# EXTS

# SQLALCHEMY
SQLALCHEMY_DATABASE_URI = "mysql://root:148574@localhost:3360/pit"
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_POOL_SIZE = 4
SQLALCHEMY_POOL_TIMEOUT = 10
SQLALCHEMY_POOL_RECYCLE = 14400
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
